In [1]:
pip install numpy

  Using cached https://files.pythonhosted.org/packages/45/b2/6c7545bb7a38754d63048c7696804a0d947328125d81bf12beaa692c3ae3/numpy-1.19.5-cp36-cp36m-manylinux1_x86_64.whl
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

# Primer punto

In [3]:
def funcion1 (A,B,c,d):
    ans = None
    ra,ca = A.shape
    rb,cb = B.shape
    #sacar las dimensiones de A y B
    if ca != rb: 
        # verificar columnas y filas
        print ("La operación no se puede realizar, las columnas de A son diferentes a las filas de B.")
        pass
    else:
        ans = np.matmul ((A**c), (B**d))
        #Realizar producto matricial
        print (ans)
    return ans


In [4]:
#Crear matrices
A = np.array([[0.1 ,2 ],[2 ,0.1]])
B = np.array ([[1,2,3],[4,5,6]])
C = np.array([[5/3 , 2/3],[5/3 , 2/3]])

# Segundo punto
    

In [5]:
#i
ans = funcion1(A,np.transpose(B),1,1)


La operación no se puede realizar, las columnas de A son diferentes a las filas de B.


In [6]:
#ii
ans = funcion1(A,B,2,1)

[[16.01 20.02 24.03]
 [ 4.04  8.05 12.06]]


In [7]:
#iii
ans = funcion1(B,C,1,3)

La operación no se puede realizar, las columnas de A son diferentes a las filas de B.


In [8]:
#iv
ans = funcion1(np.transpose(B),C,1,4)

[[38.58024691  0.98765432]
 [54.01234568  1.38271605]
 [69.44444444  1.77777778]]


In [11]:
def funcion2 (A,B):
    ans  = None
    c = input ("Ingrese el valor que desea para c.")
    d = input ("Ingrese el valor que desea para d.")
    if int (c) == float(c)  and int (d) == float(d):
        c = float (c)
        d = float (d)
        ans = funcion1(A,B,c,d)
        print (ans)
        
    else:
        print ("Ingrese valores numéricos que sean enteros")
        funcion2(A,B)
    return ans
        

In [15]:
ans = funcion2(A,B)

Ingrese el valor que desea para c.1
Ingrese el valor que desea para d.1
[[ 8.1 10.2 12.3]
 [ 2.4  4.5  6.6]]
[[ 8.1 10.2 12.3]
 [ 2.4  4.5  6.6]]


# Tercer punto


In [46]:
A = np.array([[3,2,2],[-2,1,4],[1,0,3],[5,-2,1]])


In [47]:
#a 
auxa =  np.copy(A) 
auxa[0]  =  A[0]*(2)
auxa



array([[ 6,  4,  4],
       [-2,  1,  4],
       [ 1,  0,  3],
       [ 5, -2,  1]])

In [48]:
#b
auxb = np.copy(A) 
auxb[1]  =  A[1] + 3*A[0] 
auxb 



array([[ 3,  2,  2],
       [ 7,  7, 10],
       [ 1,  0,  3],
       [ 5, -2,  1]])

In [49]:
#c
auxc = np.copy(A) 
auxc[2]  =  A[2] - A[0] 
auxc 


array([[ 3,  2,  2],
       [-2,  1,  4],
       [-2, -2,  1],
       [ 5, -2,  1]])

In [50]:
#d
auxd  = np.copy(A) 
auxd[3] = A[3]-4*A[0] 
auxd 


array([[  3,   2,   2],
       [ -2,   1,   4],
       [  1,   0,   3],
       [ -7, -10,  -7]])

In [54]:
#e
auxe = np.copy(A) 
aux1 = np.copy(A[3])
auxe[3] = A[1]
auxe[1] = aux1
auxe 

array([[ 3,  2,  2],
       [ 5, -2,  1],
       [ 1,  0,  3],
       [-2,  1,  4]])